spring:
  profiles:
    active: prod
  datasource:
    url: jdbc:h2:mem:como;MODE=MySQL;
    username: sa
    password:
    driverClassName: org.h2.Driver

  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MariaDBDialect
      database-platform: org.hibernate.dialect.H2Dialect
      ddl-auto: update
      generate-ddl: true

  thymeleaf:
    cache: false
    enabled: true
    prefix: classpath:/templates/